// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:396d1ffe-f97c-43a4-bf67-daa63f29618f",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_pg9fXwX1d",
    "aws_user_pools_web_client_id": "3euig5n7ifvmokk6urajvr35af"
};


export default awsmobile;
