projects:
  ChatApp:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: vjwffxlo4fh25jw6qylaeny2zi
        codeGenTarget: typescript
        generatedFileName: src\API.ts
        docsFilePath: src\graphql
        region: us-west-2
      endpoints:
        prod: >-
          https://gpv7wgxa6raotbn6xrcilw3rdm.appsync-api.us-west-2.amazonaws.com/graphql
